[tool.poetry]
name = "dexa-sdk"
version = "0.1.0"
description = "Store and manage Data Exchange Agreements (DEXA)"
authors = ["George J Padayatti <george.padayatti@igrant.io>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
marshmallow = "^3.17.0"
asynctest = "^0.13.0"
pytest = "^7.1.2"
green = "^3.4.2"
rich = "^12.5.1"

[tool.poetry.dev-dependencies]
autopep8 = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
